### ISSUE TITLE
The "Test it out" part in section 6 has a break in the URL

### ISSUE THREAD

**Issue by cassidoo** [googlecodelabs/your-first-pwapp#27] opened 2016-03-05 19:35 UTC
If you look in the "Test it out" part in section 6, you'll see that there's a break in the URL (it doesn't affect copying, but there's a break that's just causing a minor styling issue).

Screenshot:

![image](https://cloud.githubusercontent.com/assets/1454517/13549935/81d59956-e2df-11e5-9191-eaeebe435a55.png)

**Comment by petele** [comment] 2016-03-07 16:38
Fixed in master doc, will publish shortly

Dupe of #18

**Closed as completed by petele** 2016-03-07 16:38 UTC
Labels: duplicate, doc bug
